site_description: Network Automations Fabric documentation
site_name: Network Automations Fabric [NORFAB]
site_url: https://dmulyalin.github.io/NORFAB/
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/dmulyalin
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/DMulyalin
markdown_extensions:
- admonition
- pymdownx.details
- attr_list
- md_in_html
- pymdownx.superfences
- tables
- pymdownx.tabbed:
    alternate_style: true
      
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
- toc:
    permalink: "¤"
plugins:
    - search
    - tags:
        tags_file: tags.md
    - mkdocstrings:
        handlers:
          python:
            options:
              show_root_toc_entry: false
              docstring_section_style: table
              docstring_style: sphinx
              members_order: source
              merge_init_into_class: true
repo_name: dmulyalin/norfab
repo_url: https://github.com/dmulyalin/norfab
site_author: Denis Mulyalin
theme:
  custom_dir: docs/overrides
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.top
  - toc.follow
  - navigation.instant
  - navigation.instant.progress
  - content.footnote.tooltips
  - content.code.copy
  - content.code.annotate
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: brown
      accent: deep orange
    - scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: orange
      accent: deep orange]
      
# -------------------------------------------------------------------
# NAVIGATION sections
# -------------------------------------------------------------------

nav:
- NORFAB: 
    - Introduction: index.md
    - Installation: norfab_installation.md
    - Getting Started: norfab_getting_started.md
    - Why use NORFAB: norfab_why_use_norfab.md
    - Distributed Deployment: norfab_distributed_deployment.md
    - Docker Deployment: norfab_docker_deployment.md
    - Help with NORFAB: norfab_help_with_norfab.md
    - Changelog: norfab_changelog.md
    - Services:
        - Services Overview: services_overview.md
        - Nornir Service: 
            - Overview: workers/nornir/services_nornir_service.md
            - Inventory: workers/nornir/services_nornir_service_inventory.md
            - Task Nornir Task: workers/nornir/services_nornir_service_tasks_task.md
            - Task Cli: workers/nornir/services_nornir_service_tasks_cli.md
            - Task Cfg: workers/nornir/services_nornir_service_tasks_cfg.md
            - Task Test: workers/nornir/services_nornir_service_tasks_test.md
            - Task Network: workers/nornir/services_nornir_service_tasks_network.md
            - Task Parse: workers/nornir/services_nornir_service_tasks_parse.md
            - Task Diagram: workers/nornir/services_nornir_service_tasks_diagram.md
            - Task File Copy: workers/nornir/services_nornir_service_tasks_file_copy.md
            - Jina2 Filters Reference: workers/nornir/services_nornir_service_jinja2_filters.md
        - Netbox Service: 
            - Overview: workers/netbox/services_netbox_service.md
            - Inventory: workers/netbox/services_netbox_service_inventory.md
            - Task GraphQL: workers/netbox/services_netbox_service_tasks_graphql.md
            - Task REST: workers/netbox/services_netbox_service_tasks_rest.md
            - Task GET Devices: workers/netbox/services_netbox_service_tasks_get_devices.md
            - Task GET Interfaces: workers/netbox/services_netbox_service_tasks_get_interfaces.md
            - Task GET Connections: workers/netbox/services_netbox_service_tasks_get_connections.md
            - Task GET Circuits: workers/netbox/services_netbox_service_tasks_get_circuits.md
            - Task GET Nornir Inventory: workers/netbox/services_netbox_service_tasks_get_nornir_inventory.md
            - Task GETNext IP: workers/netbox/services_netbox_service_tasks_get_next_ip.md
            - Task UPDATE Device Facts: workers/netbox/services_netbox_service_tasks_update_device_facts.md
            - Task UPDATE Device Interfaces: workers/netbox/services_netbox_service_tasks_update_device_interfaces.md
        - NORFAB Services:
            - MMI: services_norfab_mmi.md
            - Inventory Service: services_norfab_inventory_service.md
            - File Service: services_norfab_file_service.md
            - Jobs Service: services_norfab_jobs_service.md
            - Events Service: services_norfab_events_service.md
    - Clients:
        - NORFAB Clients: clients_overview.md
        - NORFAB Shell: clients_nfcli_overview.md
        - Python API: clients_python_api_overview.md
        - REST API: clients_rest_api_overview.md
        - ROBOT API: clients_robot_client_overview.md
- References:
    - NORFAB Inventory: reference_norfab_inventory.md
    - API Reference:
        - CORE:
          - NFAPI (Python API): api_reference_core_norfab_nfapi.md
          - Broker: api_reference_core_norfab_broker.md
          - Worker: api_reference_core_norfab_worker.md
          - Client: api_reference_core_norfab_client.md
          - Simple Inventory: api_reference_core_norfab_simple_inventory.md
          - Exceptions: api_reference_core_norfab_exceptions.md
        - Built-in Workers:
          - Nornir Worker: workers/nornir/api_reference_workers_nornir_worker.md
          - Netbox Worker: workers/netbox/api_reference_workers_netbox_worker.md
        - Built-in Clients:
          - NFCLI Client API: api_reference_clients_nfcli_client.md
          - ROBOT Client API: api_reference_clients_robot_client.md
    - Architecture:
        - NORFAB Architecture: reference_architecture_norfab.md
        - NORFAB Protocol RFC: reference_architecture_nfp.md 
- Tags: tags.md