FROM python:3.9.7-slim-bullseye

RUN apt-get update && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry --upgrade

RUN pip install --no-cache-dir norfab[nornirservice] --upgrade

ENTRYPOINT cd /etc/norfab/ && nfcli -w -l $LOG_LEVEL