FROM python:3.9.7-slim-bullseye

RUN apt-get update && \
    apt-get install --no-install-recommends -y openssh-client && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry --upgrade

RUN pip install --no-cache-dir norfab[nornirservice] --upgrade

ENV LOG_LEVEL=INFO

ENTRYPOINT cd /etc/norfab/ && nfcli --workers-list nornir-worker-1 -l $LOG_LEVEL