FROM python:3.9.7-slim-bullseye

RUN apt-get update && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry --upgrade

RUN pip install --no-cache-dir norfab[netboxservice] --upgrade

ENV LOG_LEVEL=INFO

ENTRYPOINT cd /etc/norfab/ && nfcli --workers-list netbox-worker-1,netbox-worker-2 -l $LOG_LEVEL