FROM python:3.9.7-slim-bullseye

RUN apt-get update && \
    apt-get install --no-install-recommends -y dumb-init && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry --upgrade && \
    chmod 775 /usr/bin/dumb-init && \

RUN pip install --no-cache-dir norfab --upgrade

WORKDIR "/etc/norfab/"
ENTRYPOINT ["/usr/bin/dumb-init"]

ARG LOG_LEVEL=INFO

CMD ["nfcli", "-b", "-l", ${LOG_LEVEL}]